name: acanthophis-example
channels:
  - defaults
  - conda-forge
  - bioconda
  - kdm801
dependencies:
  - python
  - snakemake
  - ncdu
  - pip
  - numpy
  - wgsim
  - samtools
  - pip:
    - msprime
