# Paths to metadata files.
metadata:
  runlib2samp_file: "fake-dataset/data/rl2s.tsv"
  sample_meta_file: "fake-dataset/data/samples.tsv"
  setfile_glob: "fake-dataset/data/setfiles/*.txt"

# Reference files
refs:
  ancestral:
    fasta: "fake-dataset/data/reference/genome.fa"
    annotation: "fake-dataset/data/reference/genome.gff"

# Paths to raw data. These should be consistent across all samples. Samples
# must have either an R1 and R2, or an interleaved (il) fastq file per run and
# library.
raw_paths:
  r1_path: "fake-dataset/data/reads/{run}/{lib}_R1.fastq.gz"
  r2_path: "fake-dataset/data/reads/{run}/{lib}_R2.fastq.gz"
  il_path: "fake-dataset/data/reads/{run}/{lib}_il.fastq.gz"


# Adaptor trimming settings.
qc:
  _DEFAULT_: # settings to use for all runs except those specifically named below.
    # these settings match the NEB NextTera oligos.
    adapter1: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
    adapter2: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
    minqual: 20
  # Example special run
  # some_run:
  #   adapter1: CTGTCTCTTATACACATCTGACGCTGCCGACGANNNNNNNNGTGTAGATCTCGGTGGTCGCCGTATCATT
  #   adapter2: CTGTCTCTTATACACATCTCCGAGCCCACGAGACNNNNNNNNATCTCGTATGCCGTCTTCTGCTTG
  #   minqual: 25


# Alignment to reference
align:
  aligners:
    - bwa
    - ngm
  refs:
    - ancestral
  samplesets:
    - all
  ngm: # tool specific settings
    sensitivity: 0.5



# Variant calling
varcall:
  
  # Per-aligner minimum MAPQ thresholds for using a read.
  minmapq:
    bwa: 30  # bwa scores approximately follow a PHRED scale (-10*log10(p))
    ngm: 10  # NGM scores are bonkers, and don't follow a particularly clear scale. in practice ~10 seems appropriate


  # Minimum base quality to count *base* in pileup
  minbq: 15 
  
  # Chunk size for parallisation across genome. Per variant caller as they take
  # have different runtime and memory requirements, and all need to fit in
  # ~12hours on a single job.
  chunksize:
    mpileup:   2000000
    freebayes:   50000
    gatk-hc: 100000000

  # The main per-sample set configuration. Here we select which variant
  # callers, aligners, and reference genomes get used, and set some parameters
  # specific to each sample set.
  samplesets:
    all:
      theta_prior: 0.001
      aligners:
        - ngm
        - bwa
      callers:
        - mpileup
        - freebayes
      refs:
        - ancestral
    ## Example from our multispecies eucalyptus work
    # AdnatariaHighCoverage:
    #   theta_prior: 0.1
    #   aligners:
    #     - bwa
    #   callers:
    #     - mpileup
    #     - freebayes
    #   refs:
    #     - E_grandis
    #     - E_melliodora


  # Filters. These are series of command line arguments to pass to bcftools
  # view. These filters apply while multiallelic variants have been decomposed
  # into multiple overlapping variant calls. This allows e.g. allele frequency
  # filters to be performed on a per-allele basis.
  filters:
    default: >
      -i 'QUAL >= 10 &&
          ALT != "." &&
          INFO/DP >= 5 &&
          INFO/AN >= 3'
