name: Workflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runsnkmk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          update-conda: true
          conda-channels: "defaults,conda-forge,bioconda,kdm801"
      
      - name: Install conda deps
        run: |
          conda install mamba
          mamba env update -n base -f fake-dataset/conda.yml
      
      - name: Create fake dataset
        run: |
          pushd fake-dataset
          snakemake -j 1 --use-conda ----conda-frontend mamba
          popd

      - name: Run demo snakemake
        run: |
          snakemake -j 1 --use-conda ----conda-frontend mamba
