name: Workflow CI

on:
  push:
    branches: "**"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runsnkmk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          update-conda: true
          conda-channels: "defaults,conda-forge,bioconda,kdm801"
      
      - name: setup and run Snakemake
        run: |
          conda install mamba pip
          pushd example
          source setup.sh
          snakemake --snakefile Snakefile -j 4 --use-conda --conda-frontend mamba
          popd

