name: Workflow CI

on:
  push:
    branches: "main"
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: setup-mamba
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: bioconda,conda-forge
          channel-priority: true
          auto-update-conda: true
            
      - name: Cache generated inputs
        id: cache-inputs
        uses: actions/cache@v3
        with:
          path: tests/rawdata
          key: rawdata-${{ hashFiles('tests/Snakefile.generate-rawdata') }}-${{ hashFiles('acanthophis/template/environment.yml') }}-${{ hashFiles('acanthophis/template/workflow/rules/envs/*.yml') }}
      
      - name: setup mamba
        shell: bash -el {0}
        run: |
          mamba init

      - name: setup data
        shell: bash -el {0}
        run: |
          mamba info
          pushd tests
          bash setup.sh
          popd

      - name: run workflow
        shell: bash -el {0}
        run: |
          pushd tests
          source test.sh
          popd

      - name: cat all log files on failure
        if: ${{ failure() }}
        run: |
           find tests/ -name '*.log' -exec tail -n 1000 {} \;
